import React, { useEffect, useState } from "react";
import { View, Text, TextInput, TouchableOpacity, StyleSheet, ScrollView, Alert, ActivityIndicator } from "react-native";
import api from "../services/api";
const empty = { nom:"", nom_en:"", epaisseur:"", categorie:"", application:"", application_en:"", prix_ttc:"", poids_unite:"", qte_conteneur:"", statut_stock:"disponible" };
export default function AdminProductsScreen() {
  const [products,setProducts]=useState([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState(null); const [loading,setLoading]=useState(false);
  const load=async()=>{setLoading(true);try{setProducts((await api.get("/products")).data)}catch(e){Alert.alert("Erreur",e.response?.data?.error||"Chargement impossible")}finally{setLoading(false)}};
  useEffect(()=>{load()},[]); const field=(key,value)=>setForm({...form,[key]:value});
  const save=async()=>{try{const payload={...form,prix_ttc:Number(form.prix_ttc),poids_unite:Number(form.poids_unite),qte_conteneur:Number(form.qte_conteneur)}; if(editing) await api.put(`/products/${editing}`,payload); else await api.post("/products",payload); setForm(empty);setEditing(null);await load();}catch(e){Alert.alert("Erreur",e.response?.data?.error||"Opération impossible")}};
  const edit=(p)=>{setEditing(p.id);setForm({...empty,...p,epaisseur:String(p.epaisseur||""),prix_ttc:String(p.prix_ttc||""),poids_unite:String(p.poids_unite||""),qte_conteneur:String(p.qte_conteneur||"")})};
  const remove=(id)=>Alert.alert("Confirmation","Supprimer ce produit ?",[{text:"Annuler",style:"cancel"},{text:"Supprimer",style:"destructive",onPress:async()=>{try{await api.delete(`/products/${id}`);await load()}catch(e){Alert.alert("Erreur",e.response?.data?.error||"Suppression impossible")}}}]);
  return <ScrollView contentContainerStyle={styles.container}><Text style={styles.title}>Produits</Text><View style={styles.form}>{Object.keys(empty).map(key=><TextInput key={key} style={styles.input} placeholder={key} value={String(form[key]??"")} onChangeText={v=>field(key,v)} keyboardType={/[prix|poids|qte|epaisseur]/.test(key)?"numeric":"default"}/>)}<TouchableOpacity style={styles.primary} onPress={save}><Text style={styles.white}>{editing?"Enregistrer":"Créer le produit"}</Text></TouchableOpacity></View>{loading?<ActivityIndicator color="#b45309"/>:products.map(p=><View key={p.id} style={styles.card}><Text style={styles.name}>{p.nom}</Text><Text>{p.categorie} · {p.prix_ttc} FCFA</Text><View style={styles.row}><TouchableOpacity style={styles.secondary} onPress={()=>edit(p)}><Text style={styles.white}>Modifier</Text></TouchableOpacity><TouchableOpacity style={styles.danger} onPress={()=>remove(p.id)}><Text style={styles.white}>Supprimer</Text></TouchableOpacity></View></View>)}</ScrollView>;
}
const styles=StyleSheet.create({container:{flexGrow:1,padding:16,backgroundColor:"#faf7f2"},title:{fontSize:26,fontWeight:"800",color:"#92400e",marginBottom:16},form:{backgroundColor:"#fff",padding:12,borderRadius:12,marginBottom:16},input:{borderWidth:1,borderColor:"#e5e5e5",borderRadius:8,padding:11,marginBottom:9},card:{backgroundColor:"#fff",padding:14,borderRadius:12,marginBottom:12},name:{fontSize:17,fontWeight:"700",marginBottom:5},row:{flexDirection:"row",gap:8,marginTop:10},primary:{backgroundColor:"#b45309",padding:11,borderRadius:8,alignItems:"center"},secondary:{backgroundColor:"#0f766e",padding:10,borderRadius:8,flex:1,alignItems:"center"},danger:{backgroundColor:"#dc2626",padding:10,borderRadius:8,flex:1,alignItems:"center"},white:{color:"#fff",fontWeight:"700"}});
